import { ModelInfo } from '../types';

/**
 * OpenAI Models
 * Updated with latest models and pricing
 * 
 * https://platform.openai.com/docs/models
 * https://platform.openai.com/docs/pricing
 */
export const OPENAI_MODELS: ModelInfo[] = [
  // GPT-5.2 Series (Latest - December 2025)
  {
    id: 'gpt-5.2-instant',
    shortName: 'gpt-5.2',
    aliases: ['gpt-5-2-instant', 'gpt-5.2-chat-latest'],
    name: 'GPT-5.2 Instant',
    provider: 'openai',
    releaseDate: '2025-12-11',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
      'reasoning',
      'vision',
    ],
    tags: ['flagship', 'fast', 'professional'],
    limits: {
      contextWindow: 400000,
      maxOutputTokens: 128000,
    },
    pricing: {
      input: 1.75,
      output: 14.0,
    },
    description: 'Speed-optimized model for routine queries like information-seeking, writing, and translation',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-2',
  },
  {
    id: 'gpt-5.2',
    aliases: ['gpt-5-2', 'gpt-5.2-thinking'],
    name: 'GPT-5.2 Thinking',
    provider: 'openai',
    releaseDate: '2025-12-11',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
      'reasoning',
      'vision',
    ],
    tags: ['flagship', 'reasoning', 'coding', 'professional'],
    limits: {
      contextWindow: 400000,
      maxOutputTokens: 128000,
    },
    pricing: {
      input: 1.75,
      output: 14.0,
    },
    description: 'Excels at complex structured work like coding, analyzing long documents, math, and planning',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-2',
  },
  {
    id: 'gpt-5.2-pro',
    aliases: ['gpt-5-2-pro'],
    name: 'GPT-5.2 Pro',
    provider: 'openai',
    releaseDate: '2025-12-11',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
      'reasoning',
      'vision',
    ],
    tags: ['flagship', 'professional', 'premium', 'coding'],
    limits: {
      contextWindow: 400000,
      maxOutputTokens: 128000,
    },
    pricing: {
      input: 21.0,
      output: 168.0,
    },
    description: 'Top-end model delivering maximum accuracy and reliability for difficult problems',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-2-pro',
  },

  // GPT-5.1 Series (November 2025)
  {
    id: 'gpt-5.1-instant',
    shortName: 'gpt-5.1',
    aliases: ['gpt-5-1-instant'],
    name: 'GPT-5.1 Instant',
    provider: 'openai',
    releaseDate: '2025-11-12',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
      'reasoning',
    ],
    tags: ['flagship', 'fast', 'reasoning'],
    limits: {
      contextWindow: 200000,
      maxOutputTokens: 32768,
    },
    pricing: {
      input: 1.5,
      output: 12.0,
    },
    description: 'Most-used model with adaptive reasoning, warmer and more intelligent',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-1',
  },
  {
    id: 'gpt-5.1-thinking',
    aliases: ['gpt-5-1-thinking'],
    name: 'GPT-5.1 Thinking',
    provider: 'openai',
    releaseDate: '2025-11-12',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
      'reasoning',
    ],
    tags: ['flagship', 'reasoning', 'coding'],
    limits: {
      contextWindow: 200000,
      maxOutputTokens: 64000,
    },
    pricing: {
      input: 2.5,
      output: 20.0,
    },
    description: 'Advanced reasoning model, easier to understand and faster on simple tasks',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-1',
  },

  // GPT-5 Series
  {
    id: 'gpt-5-2025-08-07',
    shortName: 'gpt-5',
    name: 'GPT-5',
    provider: 'openai',
    releaseDate: '2025-08-07',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
      'reasoning',
    ],
    tags: ['flagship', 'reasoning', 'coding'],
    limits: {
      contextWindow: 200000,
      maxOutputTokens: 32768,
    },
    pricing: {
      input: 1.25,
      output: 10.0,
    },
    description: 'Smartest frontier model with configurable reasoning',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5',
  },
  {
    id: 'gpt-5-mini-2025-08-07',
    shortName: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'openai',
    releaseDate: '2025-08-07',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
      'reasoning',
    ],
    tags: ['balanced', 'fast', 'reasoning'],
    limits: {
      contextWindow: 128000,
      maxOutputTokens: 16384,
    },
    pricing: {
      input: 0.25,
      output: 2.0,
    },
    description: 'Balanced performance and cost',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-mini',
  },
  {
    id: 'gpt-5-nano-2025-08-07',
    shortName: 'gpt-5-nano',
    name: 'GPT-5 Nano',
    provider: 'openai',
    releaseDate: '2025-08-07',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'function-calling',
      'streaming',
      'json-mode',
    ],
    tags: ['fast', 'cost-effective'],
    limits: {
      contextWindow: 128000,
      maxOutputTokens: 16384,
    },
    pricing: {
      input: 0.05,
      output: 0.4,
    },
    description: 'Fastest, most cost-efficient version of GPT-5',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-5-nano',
  },

  // GPT-4o Series
  {
    id: 'gpt-4o-2024-08-06',
    shortName: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    releaseDate: '2024-08-06',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'vision',
      'function-calling',
      'streaming',
      'json-mode',
    ],
    tags: ['multimodal', 'coding'],
    limits: {
      contextWindow: 128000,
      maxOutputTokens: 16384,
    },
    pricing: {
      input: 2.5,
      output: 10.0,
    },
    description: 'Most capable GPT-4o, best for complex tasks',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-4o',
  },
  {
    id: 'gpt-4o-mini-2024-07-18',
    shortName: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    releaseDate: '2024-07-18',
    status: 'stable',
    capabilities: [
      'text-generation',
      'chat',
      'code-generation',
      'vision',
      'function-calling',
      'streaming',
      'json-mode',
    ],
    tags: ['fast', 'cost-effective', 'multimodal'],
    limits: {
      contextWindow: 128000,
      maxOutputTokens: 16384,
    },
    pricing: {
      input: 0.15,
      output: 0.6,
    },
    description: 'Fast and affordable, good for most tasks',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-4o-mini',
  },

  // O1 Series (Reasoning models)
  {
    id: 'o1-2024-12-17',
    shortName: 'o1',
    name: 'O1',
    provider: 'openai',
    releaseDate: '2024-12-17',
    status: 'stable',
    capabilities: ['text-generation', 'chat', 'reasoning', 'code-generation'],
    tags: ['reasoning', 'flagship', 'coding'],
    limits: {
      contextWindow: 200000,
      maxOutputTokens: 100000,
    },
    pricing: {
      input: 15.0,
      output: 60.0,
    },
    description: 'Most advanced reasoning model for complex problem-solving',
    docsUrl: 'https://platform.openai.com/docs/models/o1',
  },
  {
    id: 'o1-mini-2024-09-12',
    shortName: 'o1-mini',
    name: 'O1 Mini',
    provider: 'openai',
    releaseDate: '2024-09-12',
    status: 'stable',
    capabilities: ['text-generation', 'chat', 'reasoning', 'code-generation'],
    tags: ['reasoning', 'cost-effective', 'coding'],
    limits: {
      contextWindow: 128000,
      maxOutputTokens: 65536,
    },
    pricing: {
      input: 3.0,
      output: 12.0,
    },
    description: 'Faster and cheaper reasoning model',
    docsUrl: 'https://platform.openai.com/docs/models/o1-mini',
  },

  // Deprecated/Legacy Models
  {
    id: 'gpt-4-turbo-2024-04-09',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    releaseDate: '2024-04-09',
    status: 'deprecated',
    capabilities: ['text-generation', 'chat', 'vision', 'function-calling', 'streaming', 'json-mode'],
    tags: ['deprecated', 'multimodal'],
    limits: {
      contextWindow: 128000,
      maxOutputTokens: 4096,
    },
    pricing: {
      input: 10.0,
      output: 30.0,
    },
    description: 'Previous generation GPT-4 Turbo, replaced by GPT-4o',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4',
    deprecationDate: '2024-08-06',
    replacementModel: 'gpt-4o-2024-08-06',
  },
  {
    id: 'gpt-4-0613',
    name: 'GPT-4',
    provider: 'openai',
    releaseDate: '2023-06-13',
    status: 'deprecated',
    capabilities: ['text-generation', 'chat', 'function-calling', 'streaming'],
    tags: ['deprecated'],
    limits: {
      contextWindow: 8192,
      maxOutputTokens: 4096,
    },
    pricing: {
      input: 30.0,
      output: 60.0,
    },
    description: 'Original GPT-4 model, replaced by newer versions',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4',
    deprecationDate: '2024-06-13',
    replacementModel: 'gpt-4o-2024-08-06',
  },
  {
    id: 'gpt-3.5-turbo-0125',
    name: 'GPT-3.5 Turbo',
    provider: 'openai',
    releaseDate: '2024-01-25',
    status: 'deprecated',
    capabilities: ['text-generation', 'chat', 'function-calling', 'streaming', 'json-mode'],
    tags: ['deprecated', 'cost-effective'],
    limits: {
      contextWindow: 16385,
      maxOutputTokens: 4096,
    },
    pricing: {
      input: 0.5,
      output: 1.5,
    },
    description: 'Latest GPT-3.5 model, superseded by GPT-4o mini',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-3-5-turbo',
    deprecationDate: '2024-09-13',
    shutdownDate: '2025-09-13',
    replacementModel: 'gpt-4o-mini-2024-07-18',
  },
  {
    id: 'gpt-3.5-turbo-instruct',
    name: 'GPT-3.5 Turbo Instruct',
    provider: 'openai',
    releaseDate: '2023-09-01',
    status: 'deprecated',
    capabilities: ['text-generation', 'streaming'],
    tags: ['deprecated'],
    limits: {
      contextWindow: 4096,
      maxOutputTokens: 4096,
    },
    pricing: {
      input: 1.5,
      output: 2.0,
    },
    description: 'Instruction-following model, replaced by chat models',
    docsUrl: 'https://platform.openai.com/docs/models/gpt-3-5-turbo',
    deprecationDate: '2024-01-04',
    replacementModel: 'gpt-4o-mini-2024-07-18',
  },
  {
    id: 'text-davinci-003',
    name: 'Davinci 003',
    provider: 'openai',
    releaseDate: '2022-11-28',
    status: 'disabled',
    capabilities: ['text-generation'],
    tags: ['deprecated'],
    limits: {
      contextWindow: 4097,
      maxOutputTokens: 4097,
    },
    pricing: {
      input: 20.0,
      output: 20.0,
    },
    description: 'Legacy GPT-3 model, shut down January 2024',
    docsUrl: 'https://platform.openai.com/docs/deprecations',
    deprecationDate: '2023-07-06',
    shutdownDate: '2024-01-04',
    replacementModel: 'gpt-3.5-turbo-instruct',
  },

  // Embedding Models
  {
    id: 'text-embedding-3-large',
    name: 'Text Embedding 3 Large',
    provider: 'openai',
    releaseDate: '2024-01-25',
    status: 'stable',
    capabilities: ['embeddings'],
    tags: ['flagship'],
    limits: {
      contextWindow: 8191,
      maxOutputTokens: 0,
    },
    pricing: {
      input: 0.13,
      output: 0.0,
    },
    description: 'Most capable embedding model, 3072 dimensions, improved performance',
    docsUrl: 'https://platform.openai.com/docs/models/embeddings',
  },
  {
    id: 'text-embedding-3-small',
    name: 'Text Embedding 3 Small',
    provider: 'openai',
    releaseDate: '2024-01-25',
    status: 'stable',
    capabilities: ['embeddings'],
    tags: ['cost-effective', 'fast'],
    limits: {
      contextWindow: 8191,
      maxOutputTokens: 0,
    },
    pricing: {
      input: 0.02,
      output: 0.0,
    },
    description: 'Efficient embedding model, 1536 dimensions, 5x cheaper than ada-002',
    docsUrl: 'https://platform.openai.com/docs/models/embeddings',
  },
  {
    id: 'text-embedding-ada-002',
    name: 'Text Embedding Ada 002',
    provider: 'openai',
    releaseDate: '2022-12-15',
    status: 'stable',
    capabilities: ['embeddings'],
    tags: ['deprecated'],
    limits: {
      contextWindow: 8191,
      maxOutputTokens: 0,
    },
    pricing: {
      input: 0.10,
      output: 0.0,
    },
    description: 'Legacy embedding model, 1536 dimensions, replaced by v3 models',
    docsUrl: 'https://platform.openai.com/docs/models/embeddings',
    deprecationDate: '2024-01-25',
    replacementModel: 'text-embedding-3-small',
  },
];
