import { ProviderInfo } from './types';

/**
 * Information about AI model providers
 */
export const PROVIDERS: ProviderInfo[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    website: 'https://openai.com',
    apiBaseUrl: 'https://api.openai.com/v1',
    apiDocsUrl: 'https://platform.openai.com/docs',
    modelsEndpoint: 'https://api.openai.com/v1/models',
    icon: '🤖',
    color: '#10a37f',
    description: 'Leading AI research company, creators of GPT models and ChatGPT',
    features: [
      'Chat completion',
      'Text generation',
      'Code generation',
      'Vision',
      'Function calling',
      'JSON mode',
      'Audio (Whisper)',
      'Image generation (DALL-E)',
      'Embeddings',
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    website: 'https://anthropic.com',
    apiBaseUrl: 'https://api.anthropic.com',
    apiDocsUrl: 'https://docs.anthropic.com',
    modelsEndpoint: 'https://api.anthropic.com/v1/models',
    icon: '🧠',
    color: '#cc785c',
    description: 'AI safety company, creators of Claude models with strong reasoning capabilities',
    features: [
      'Chat completion',
      'Extended reasoning',
      'Vision',
      'Function calling',
      'JSON mode',
      'Prompt caching',
      'Extended context (200K tokens)',
    ],
  },
  {
    id: 'google',
    name: 'Google AI',
    website: 'https://ai.google.dev',
    apiBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    apiDocsUrl: 'https://ai.google.dev/docs',
    modelsEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models',
    icon: '🔷',
    color: '#4285f4',
    description: 'Google\'s AI division, creators of Gemini models with massive context windows',
    features: [
      'Chat completion',
      'Vision',
      'Audio input',
      'Function calling',
      'JSON mode',
      'Extended context (up to 2M tokens)',
      'Grounding with Google Search',
    ],
  },
  {
    id: 'xai',
    name: 'xAI',
    website: 'https://x.ai',
    apiBaseUrl: 'https://api.x.ai/v1',
    apiDocsUrl: 'https://docs.x.ai',
    modelsEndpoint: 'https://api.x.ai/v1/models',
    icon: '🅧',
    color: '#000000',
    description: 'Elon Musk\'s AI company, creators of Grok models with real-time knowledge',
    features: [
      'Chat completion',
      'Real-time web search',
      'Extended context',
      'Function calling',
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    website: 'https://mistral.ai',
    apiBaseUrl: 'https://api.mistral.ai/v1',
    apiDocsUrl: 'https://docs.mistral.ai',
    modelsEndpoint: 'https://api.mistral.ai/v1/models',
    icon: '⚡',
    color: '#ff7000',
    description: 'European AI company focused on efficient and powerful open models',
    features: [
      'Chat completion',
      'Function calling',
      'JSON mode',
      'Embeddings',
      'Moderation',
    ],
  },
  {
    id: 'zai',
    name: 'Z.AI',
    website: 'https://z.ai',
    apiBaseUrl: 'https://api.z.ai/v1',
    apiDocsUrl: 'https://z.ai/model-api',
    icon: '🇿',
    color: '#6366f1',
    description: 'Chinese AI provider with competitive pricing and strong performance',
    features: [
      'Chat completion',
      'Code generation',
      'Function calling',
      'JSON mode',
      'Cost-effective pricing',
    ],
  },
  {
    id: 'meta',
    name: 'Meta AI',
    website: 'https://ai.meta.com',
    apiBaseUrl: 'https://api.llama.com/v1/',
    apiDocsUrl: 'https://llama.developer.meta.com/docs/overview/',
    modelsEndpoint: 'https://api.llama.com/v1/models',
    icon: '🦙',
    color: '#0668e1',
    description: 'Meta\'s open-source Llama models available through various providers',
    features: [
      'Chat completion',
      'Code generation',
      'Vision (Llama 3.2)',
      'Open source',
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    website: 'https://www.deepseek.com',
    apiBaseUrl: 'https://api.deepseek.com/v1',
    apiDocsUrl: 'https://platform.deepseek.com/docs',
    modelsEndpoint: 'https://api.deepseek.com/models',
    icon: '🔍',
    color: '#1a73e8',
    description: 'Chinese AI company known for extremely cost-effective models with reasoning',
    features: [
      'Chat completion',
      'Reasoning',
      'Code generation',
      'Extended context',
      'Ultra-low pricing',
    ],
  },
];
